# Generated by Django 4.2.3 on 2024-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='keyLog',
        ),
    ]
