# Generated by Django 4.2.3 on 2024-05-26 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keylogger_app', '0002_loggedkeys_delete_keylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedKeys',
        ),
    ]
